<?php

namespace AppBundle\Repository;

/**
 * EtiketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtiketRepository extends \Doctrine\ORM\EntityRepository
{
}
