<?php

namespace AppBundle\Repository;

/**
 * IzinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IzinRepository extends \Doctrine\ORM\EntityRepository
{
}
