<?php

namespace AppBundle\Repository;

/**
 * UyeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UyeRepository extends \Doctrine\ORM\EntityRepository
{
}
